# pro enviroment
server:
  port: 8081

spring:
  application:
    name: vuebg-client
  #  zipkin:
  #    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://192.168.200.112:3306/suphowe?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
    healthcheck:        #开启健康检查
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vuebg.client.entity

# 日志
logging:
  config: classpath:log-config.xml