# develop enviroment
server:
  port: 8710

spring:
  application:
    name: vuebg-backup
#  zipkin:
#    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://192.168.200.112:3306/suphowe?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
    healthcheck:        #开启健康检查
      enabled: true

# backup datasource
vuebg:
  backup:
    datasource:
      host: 192.168.200.112
      userName: root
      password: root
      database: suphowe