eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

server:
  port: 8720

spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: vuebg-client

    api-b:
      path: /api-b/**
      serviceId: vuebg-admin